name: Start Relay

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
name: Checkout code
    uses: actions/checkout@v2,

    
name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.x',

    
name: Install cloudflared
    run: |
      wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
      chmod +x cloudflared-linux-amd64
      sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared,

    
name: Run Relay Server
    run: |
      nohup python StartRelay.py &,

    
name: Start Cloudflare Tunnel
    run: |
      cloudflared tunnel --url tcp://localhost:3334 --no-autoupdate